name: 'e2e'
description: 'A github action to run a flux e2e'
inputs:
  clusterPath:
    description: 'cluster path like ./clusters/dev or ./clusters/staging'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup tools
      uses: ./.github/actions/tools
    - name: Setup Flux
      uses: fluxcd/flux2/action@main
    - name: Setup Kubernetes
      uses: engineerd/setup-kind@v0.5.0
      with:
        version: "v0.11.1"
    - name: Install Flux in Kubernetes Kind
      shell: bash
      run: flux install
    - name: Setup cluster reconciliation
      shell: bash
      run: |
        flux create source git flux-system \
        --url=${{ github.event.repository.html_url }} \
        --branch=${GITHUB_REF#refs/heads/}
        flux create kustomization flux-system \
        --source=flux-system \
        --path=${{ inputs.clusterPath }}
